### ISSUE TITLE
Command for ffmpeg

### ISSUE THREAD

**Issue by iwanttobefreak** [jumpjack/fishconLC#1]
Hello. Can you share the command of ffmpeg to convert a fisheye image to equirectangular?
![360_0063](https://github.com/jumpjack/fishconLC/assets/13958712/6456fd9a-0880-459a-8b6a-b6238f7b4d5c)
![equirectangular](https://github.com/jumpjack/fishconLC/assets/13958712/b8012264-9bf1-414a-b79c-62420323df8c)
Thanks!

**Comment by jumpjack** [comment]
It's at the bottom of main page of the repository:

`ffmpeg -i input.jpg -y output.jpg -vf v360=fisheye:equirectangular:ih_fov=235:v_fov=235:yaw=0:pitch=90:roll=0`

Just change "fisheye" to "dfisheye".

```
-vf v360: filter name
dfisheye: source projection  (double fisheye)
equirectangular: final projection
ih_fov=235: horizontal FOV of input
iv_fov=235: horizontal FOV of inputr 
yaw=0:
pitch=90:
roll=0```

Try with yaw, pitch and roll =0 and ih_fov and iv_fov=180 to start.

Adjust yaw, pitch and roll to make horizon horizontal.
Adjust  ih_fov and iv_fov to remove "stitching line".

The best I could find for that image is:

ffmpeg -i fisheye1.jpg -vf v360=dfisheye:e:ih_fov=193:iv_fov=193 -y out6.jpg

**Comment by jumpjack** [comment]
You can experiment here:

https://ffmpeg.lav.io/

It's for videos, but you can also upload images.

**Comment by iwanttobefreak** [comment]
A lot of thanks. This ffmpeg command works fine

**Comment by iwanttobefreak** [comment]
A lot thanks. This ffmpeg command works.
